zalando-stups/fullstop

fullstop-plugin-api/src/main/java/org/zalando/stups/fullstop/aws/ClientProvider.java
fullstop-plugin-api/src/main/java/org/zalando/stups/fullstop/aws/ClientProviderImpl.java
fullstop-plugins/fullstop-instance-plugin/pom.xml
fullstop-plugins/fullstop-instance-plugin/src/main/java/org/zalando/stups/fullstop/plugin/RunInstancePlugin.java
fullstop/src/main/java/org/zalando/stups/fullstop/AwsCloudTrailProcessingExecutorContainer.java
fullstop/src/main/java/org/zalando/stups/fullstop/ExtPropertiesFileConfiguration.java
fullstop/src/main/java/org/zalando/stups/fullstop/Fullstop.java
fullstop/src/main/java/org/zalando/stups/fullstop/FullstopConfig.java
fullstop/src/main/java/org/zalando/stups/fullstop/PluginEventsProcessor.java
fullstop/src/test/java/org/zalando/stups/fullstop/SimpleFullstopIT.java
fullstop/src/test/java/org/zalando/stups/fullstop/plugin/example/ExamplePlugin.java
fullstop/src/test/java/org/zalando/stups/fullstop/plugin/example/ExamplePluginRegistryTest.java

credential provider not using temporary credential for current account
run instances plugin

run instances plugin

---

fullstop-plugin-api/src/main/java/org/zalando/stups/fullstop/aws/ClientProvider.java
fullstop-plugin-api/src/main/java/org/zalando/stups/fullstop/aws/ClientProviderImpl.java
fullstop-plugin-api/src/main/java/org/zalando/stups/fullstop/plugin/FullstopPlugin.java
fullstop-plugins/fullstop-instance-plugin/pom.xml
fullstop-plugins/fullstop-instance-plugin/src/main/java/org/zalando/stups/fullstop/plugin/RunInstancePlugin.java
fullstop-plugins/fullstop-instance-plugin/src/test/java/org/zalando/stups/FileEventReader.java
fullstop-plugins/fullstop-instance-plugin/src/test/java/org/zalando/stups/FileEventReaderTest.java
fullstop-plugins/fullstop-instance-plugin/src/test/java/org/zalando/stups/LogFiles.java
fullstop-plugins/pom.xml
fullstop-processing/pom.xml
fullstop-processing/src/main/java/org/zalando/stups/fullstop/AwsCloudTrailProcessingExecutorContainer.java
fullstop-processing/src/main/java/org/zalando/stups/fullstop/CloudTrailProcessingLibraryProperties.java
fullstop-processing/src/main/java/org/zalando/stups/fullstop/ExtPropertiesFileConfiguration.java
fullstop-processing/src/main/java/org/zalando/stups/fullstop/FullstopConfig.java
fullstop-processing/src/main/java/org/zalando/stups/fullstop/FullstopContainerProperties.java
fullstop-processing/src/main/java/org/zalando/stups/fullstop/PluginEventsProcessor.java
fullstop-processing/src/main/java/org/zalando/stups/fullstop/SimplePropertiesCredentials.java
fullstop-processing/src/test/java/org/zalando/stups/fullstop/plugin/example/ExamplePlugin.java
fullstop-processing/src/test/java/org/zalando/stups/fullstop/plugin/example/ExamplePluginRegistryTest.java
fullstop-processing/src/test/java/org/zalando/stups/fullstop/plugin/example/ExamplePluginTest.java
fullstop-test-support/pom.xml
fullstop-test-support/src/main/java/org/zalando/stups/fullstop/events/FileEventReader.java
fullstop/src/main/java/org/zalando/stups/fullstop/Fullstop.java
fullstop/src/test/java/org/zalando/stups/fullstop/SimpleFullstopIT.java
pom.xml
src/etc/header.txt

Many modules moved and restructured to handle dependencies and make testing easier.

Merge testing branch

---

fullstop-plugin-api/src/main/java/org/zalando/stups/fullstop/plugin/AbstractFullstopPlugin.java
fullstop-plugins/fullstop-ami-plugin/src/main/java/org/zalando/stups/fullstop/plugin/AmiPlugin.java
fullstop-plugins/fullstop-hello-event-plugin/src/main/java/org/zalando/stups/fullstop/plugin/hello/HelloEventPlugin.java
fullstop-plugins/fullstop-instance-plugin/src/main/java/org/zalando/stups/fullstop/plugin/RunInstancePlugin.java
fullstop-processing/src/main/java/org/zalando/stups/fullstop/PluginEventsProcessor.java
fullstop-processing/src/test/java/org/zalando/stups/fullstop/plugin/example/ExamplePlugin.java

storing results of processing, so nothing has to be returned, introduced
AbstractFullstopPlugin to handle common code for implementations (like
reading plugin-metadata from descriptor), all existing plugins in
project updated to new signature

changed signature to make clear that the plugin itself has to care about

---

fullstop-timemachine/src/main/java/org/zalando/stups/fullstop/swagger/api/FullstopApi.java
fullstop-timemachine/src/test/java/org/zalando/stups/fullstop/swagger/api/FullstopApiTest.java

api returns a page instead of a list

---

fullstop-timemachine/src/main/java/org/zalando/stups/fullstop/swagger/api/FullstopApi.java
fullstop-timemachine/src/test/java/org/zalando/stups/fullstop/swagger/api/FullstopApiTest.java
fullstop-violation/src/main/java/org/zalando/stups/fullstop/violation/service/ViolationService.java
fullstop-violation/src/main/java/org/zalando/stups/fullstop/violation/service/impl/ViolationServiceImpl.java

#128 resolution returns violation

---

fullstop-plugins/fullstop-count-events-plugin/src/main/java/org/zalando/stups/fullstop/plugin/count/CountEventsMetric.java
fullstop-plugins/fullstop-count-events-plugin/src/main/java/org/zalando/stups/fullstop/plugin/count/CountEventsPlugin.java
fullstop-plugins/fullstop-registry-plugin/pom.xml
fullstop-plugins/fullstop-registry-plugin/src/main/java/org/zalando/stups/fullstop/plugin/RegistryPlugin.java
fullstop-violation-persister-jpa/src/main/java/org/zalando/fullstop/violation/persist/jpa/ViolationJpaPersister.java
fullstop-violation-persister-jpa/src/main/java/org/zalando/fullstop/violation/persist/jpa/config/ViolationJpaPersisterAutoConfiguration.java
fullstop-violation-sink-reactor/pom.xml
fullstop-violation-sink-reactor/src/main/java/org/zalando/stups/fullstop/violation/reactor/EventBusViolationHandler.java
fullstop-violation-sink-reactor/src/main/java/org/zalando/stups/fullstop/violation/reactor/EventBusViolationSink.java
fullstop-violation-sink-reactor/src/test/java/com/unknown/comp/HandlerConfig.java
fullstop-violation-sink-reactor/src/test/java/com/unknown/comp/SimpleDemonstrationViolationHandler.java
fullstop/pom.xml

update version to latest release, surround with try-catch for all

---

fullstop-plugins/fullstop-registry-plugin/pom.xml
fullstop/pom.xml
pom.xml

update pierone-client, clean-up poms and declare versions in

---

README.md
fullstop-timemachine/pom.xml
fullstop-timemachine/src/main/java/org/zalando/stups/fullstop/swagger/api/ApiException.java
fullstop-timemachine/src/main/java/org/zalando/stups/fullstop/swagger/api/ForbiddenException.java
fullstop-timemachine/src/main/java/org/zalando/stups/fullstop/swagger/api/FullstopApi.java
fullstop-timemachine/src/main/java/org/zalando/stups/fullstop/teams/InfrastructureAccount.java
fullstop-timemachine/src/main/java/org/zalando/stups/fullstop/teams/RestTemplateTeamOperations.java
fullstop-timemachine/src/main/java/org/zalando/stups/fullstop/teams/TeamOperations.java
fullstop-timemachine/src/main/java/org/zalando/stups/fullstop/teams/UserTeam.java
fullstop-timemachine/src/test/java/org/zalando/stups/fullstop/common/RestControllerTestSupport.java
fullstop-timemachine/src/test/java/org/zalando/stups/fullstop/swagger/api/FullstopApiTest.java
fullstop/pom.xml
fullstop/src/main/java/org/zalando/stups/fullstop/Fullstop.java
fullstop/src/main/java/org/zalando/stups/fullstop/config/ClientConfig.java
fullstop/src/main/resources/config/application.yml
pom.xml

#132 violations by teams

---

fullstop-plugins/fullstop-registry-plugin/src/main/java/org/zalando/stups/fullstop/plugin/RegistryPlugin.java
fullstop-plugins/fullstop-registry-plugin/src/test/java/org/zalando/stups/fullstop/plugin/RegistryPluginApprovalsTest.java
fullstop-plugins/fullstop-registry-plugin/src/test/java/org/zalando/stups/fullstop/plugin/RegistryPluginKioTest.java
pom.xml

N eyes principle

---

fullstop-timemachine/src/main/java/org/zalando/stups/fullstop/swagger/api/FullstopApi.java

with ignoring in the web section you should not use security annotation on method

remove permitt all

---

bash_libs/interrupt.sh
build-docker-image.sh

As a user who execute this script I want to press ctrl+c only one time.

Add trap to press ctrl+c once

---

fullstop-plugins/fullstop-application-lifecycle-plugin/src/main/java/org/zalando/stups/fullstop/plugin/LifecyclePlugin.java
fullstop-plugins/fullstop-application-lifecycle-plugin/src/test/java/org/zalando/stups/fullstop/plugin/LifecyclePluginTest.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/service/impl/ApplicationLifecycleServiceImpl.java
fullstop-violation/fullstop-violation-jpa/src/test/java/org/zalando/stups/fullstop/violation/service/impl/ApplicationLifecycleServiceImplTest.java

- fixed nullpointer when userdata cotains null values
- fixed broken base64 decoder

fixes for application lifecycle.

---

fullstop-parent-poms/fullstop-parent/pom.xml
fullstop-plugins/fullstop-registry-plugin/src/main/java/org/zalando/stups/fullstop/plugin/RegistryPlugin.java
fullstop-plugins/fullstop-scm-repository-plugin/src/main/java/org/zalando/stups/fullstop/plugin/scm/ScmRepositoryPlugin.java
fullstop-plugins/fullstop-scm-repository-plugin/src/test/java/org/zalando/stups/fullstop/plugin/scm/ScmRepositoryPluginTest.java
fullstop-testing/it/fullstop-it-autoshutdown/pom.xml
fullstop-testing/it/fullstop/pom.xml
fullstop-testing/it/fullstop/src/main/java/org/zalando/stups/fullstop/config/ClientConfig.java
fullstop-testing/it/fullstop/src/main/java/org/zalando/stups/fullstop/hystrix/HystrixKioOperations.java
fullstop-testing/it/fullstop/src/test/java/org/zalando/stups/fullstop/config/HystrixConfigurationTest.java
fullstop-testing/it/fullstop/src/test/java/org/zalando/stups/fullstop/config/OAuth2RestTemplateIntegrationTest.java
fullstop-testing/it/pom.xml
fullstop-testing/pom.xml
pom.xml

sorry for the confusing commit message. Was in cache ;-)

fix kio client 404 handling

---

fullstop-plugins/fullstop-application-lifecycle-plugin/src/main/java/org/zalando/stups/fullstop/plugin/LifecyclePlugin.java
fullstop-plugins/fullstop-application-lifecycle-plugin/src/test/java/org/zalando/stups/fullstop/plugin/LifecyclePluginTest.java

Minor refactorings

---

fullstop-api.yaml
fullstop-testing/it/fullstop/src/main/resources/logback.xml
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/entity/CountByAppVersionAndType.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/repository/ViolationRepositoryCustom.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/repository/impl/ViolationRepositoryImpl.java
fullstop-violation/fullstop-violation-jpa/src/test/java/org/zalando/stups/fullstop/violation/repository/ViolationRepositoryTest.java
fullstop-web/fullstop-violations-rest/src/main/java/org/zalando/stups/fullstop/web/controller/ViolationsCountController.java
fullstop-web/fullstop-violations-rest/src/test/java/org/zalando/stups/fullstop/web/controller/ViolationsCountControllerTest.java

#259 count violations by app version and type

---

fullstop-apis/fullstop-plugin-api/pom.xml
fullstop-apis/fullstop-violation-api/pom.xml
fullstop-aws-support/pom.xml
fullstop-core/pom.xml
fullstop-job-launcher/pom.xml
fullstop-jobs/pom.xml
fullstop-parent-poms/fullstop-parent/pom.xml
fullstop-plugins/fullstop-registry-plugin/src/main/java/org/zalando/stups/fullstop/plugin/RegistryPlugin.java
fullstop-plugins/fullstop-registry-plugin/src/test/java/org/zalando/stups/fullstop/plugin/RegistryPluginPieroneTest.java
fullstop-plugins/pom.xml
fullstop-testing/it/fullstop/src/main/java/org/zalando/stups/fullstop/hystrix/HystrixPieroneOperations.java
fullstop-testing/it/fullstop/src/test/java/org/zalando/stups/fullstop/hystrix/HystrixPieroneOperationsTest.java
fullstop-testing/it/pom.xml
fullstop-testing/pom.xml
fullstop-violation/pom.xml
fullstop-web/fullstop-timemachine/pom.xml
fullstop-web/fullstop-violations-rest/pom.xml
fullstop-web/fullstop-web-commons/pom.xml
fullstop-web/fullstop-web-test-support/pom.xml
pom.xml
team-service-api/pom.xml
teams-service-client-spring/pom.xml

#270 update dependencies

---

fullstop-plugins/fullstop-snapshot-source-plugin/src/main/java/org/zalando/stups/fullstop/plugin/snapshot/SnapshotSourcePlugin.java

#268 missing metadata

---

fullstop-plugins/fullstop-registry-plugin/src/test/java/org/zalando/stups/fullstop/plugin/RegistryPluginPieroneTest.java

#280 added unit test to verify correct behavior on missing docker:// prefix

---

fullstop-plugins/fullstop-application-lifecycle-plugin/src/main/java/org/zalando/stups/fullstop/plugin/LifecyclePlugin.java

#292 - fix array out of bound

---

fullstop-apis/fullstop-violation-api/src/main/java/org/zalando/stups/fullstop/violation/ViolationType.java
fullstop-aws-support/fullstop-aws-cloudtrail-support/src/main/java/org/zalando/stups/fullstop/events/CloudTrailEventSupport.java
fullstop-aws-support/fullstop-aws-cloudtrail-support/src/test/java/org/zalando/stups/fullstop/events/CloudTrailEventSupportTest.java
fullstop-plugins/fullstop-ami-plugin/src/main/java/org/zalando/stups/fullstop/plugin/ami/AmiPlugin.java
fullstop-plugins/fullstop-application-lifecycle-plugin/src/main/java/org/zalando/stups/fullstop/plugin/LifecyclePlugin.java
fullstop-plugins/fullstop-registry-plugin/src/main/java/org/zalando/stups/fullstop/plugin/RegistryPlugin.java
fullstop-plugins/fullstop-registry-plugin/src/main/java/org/zalando/stups/fullstop/plugin/config/RegistryPluginAutoConfiguration.java

#254 merge missing approval violations

---

fullstop-plugins/fullstop-unapproved-services-and-role-plugin/src/main/java/org/zalando/stups/fullstop/plugin/unapproved/UnapprovedServicesAndRolePlugin.java

fix exception

---

fullstop-aws-support/fullstop-aws-cloudtrail-support/src/main/java/org/zalando/stups/fullstop/events/CloudTrailEventSupport.java
fullstop-core/fullstop-processing/src/test/java/org/zalando/stups/fullstop/plugin/example/ExamplePluginRegistryTest.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/TestAsyncIT.java
fullstop-web/fullstop-timemachine/src/main/java/org/zalando/stups/fullstop/controller/S3Controller.java

#293 fix print stack trace

---

fullstop-plugins/fullstop-scm-repository-plugin/src/main/java/org/zalando/stups/fullstop/plugin/scm/ScmRepositoryPlugin.java
fullstop-plugins/fullstop-unapproved-services-and-role-plugin/src/main/java/org/zalando/stups/fullstop/plugin/unapproved/UnapprovedServicesAndRolePlugin.java

#300 fixed metadata in plugins

---

fullstop-plugins/fullstop-instance-plugin-support/src/main/java/org/zalando/stups/fullstop/plugin/provider/impl/KioApplicationProviderImpl.java
fullstop-plugins/fullstop-instance-plugin-support/src/main/java/org/zalando/stups/fullstop/plugin/provider/impl/KioApprovalProviderImpl.java
fullstop-plugins/fullstop-instance-plugin-support/src/main/java/org/zalando/stups/fullstop/plugin/provider/impl/KioVersionProviderImpl.java
fullstop-plugins/fullstop-instance-plugin-support/src/test/java/org/zalando/stups/fullstop/plugin/provider/impl/KioApplicationProviderImplTest.java
fullstop-plugins/fullstop-instance-plugin-support/src/test/java/org/zalando/stups/fullstop/plugin/provider/impl/KioApprovalProviderImplTest.java
fullstop-plugins/fullstop-instance-plugin-support/src/test/java/org/zalando/stups/fullstop/plugin/provider/impl/KioVersionProviderImplTest.java

#302 catch all NotFoundExceptions

---

fullstop-plugins/fullstop-ami-plugin/src/main/java/org/zalando/stups/fullstop/plugin/ami/AmiPlugin.java
fullstop-plugins/fullstop-ami-plugin/src/test/java/org/zalando/stups/fullstop/plugin/ami/AmiPluginTest.java

#305 added ami owner id to metadata.

---

fullstop-violation/fullstop-violation-jpa/pom.xml
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/entity/ApplicationEntity.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/entity/VersionEntity.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/service/impl/ApplicationLifecycleServiceImpl.java
fullstop-violation/fullstop-violation-jpa/src/test/java/org/zalando/stups/fullstop/violation/service/impl/SaveApplicationLifecycleRetryTest.java

#306 using retry mechanism

---

fullstop-apis/fullstop-violation-api/src/main/java/org/zalando/stups/fullstop/violation/DefaultViolation.java
fullstop-apis/fullstop-violation-api/src/main/java/org/zalando/stups/fullstop/violation/Violation.java
fullstop-testing/it/fullstop/src/main/resources/db/migration/V4__create_rule_table.sql
fullstop-testing/it/fullstop/src/main/resources/db/migration/V5__set_audit_relevant_for_violation_types.sql
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/domain/AbstractCreatableEntity.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/domain/AbstractEntity.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/domain/AbstractModifiableEntity.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/domain/validation/groups/PersistenceOnly.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/rule/entity/RuleEntity.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/rule/repository/RuleEntityRepository.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/entity/ApplicationEntity.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/entity/LifecycleEntity.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/entity/VersionEntity.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/entity/ViolationEntity.java
fullstop-violation/fullstop-violation-persister-jpa/pom.xml
fullstop-violation/fullstop-violation-persister-jpa/src/main/java/org/zalando/fullstop/violation/persist/jpa/ViolationJpaPersister.java
fullstop-violation/fullstop-violation-persister-jpa/src/main/java/org/zalando/fullstop/violation/persist/jpa/config/ViolationJpaPersisterAutoConfiguration.java
fullstop-web/fullstop-web-test-support/src/main/java/org/zalando/stups/fullstop/web/test/builder/AbstractCreatableEntityBuilder.java
fullstop-web/fullstop-web-test-support/src/main/java/org/zalando/stups/fullstop/web/test/builder/AbstractEntityBuilder.java
fullstop-web/fullstop-web-test-support/src/main/java/org/zalando/stups/fullstop/web/test/builder/AbstractModifiableEntityBuilder.java
fullstop-whitelist/pom.xml
fullstop-whitelist/src/main/java/org/zalando/stups/fullstop/whitelist/RuleDataProvider.java
fullstop-whitelist/src/main/java/org/zalando/stups/fullstop/whitelist/config/WhitelistConfig.java
fullstop-whitelist/src/main/resources/drools/TaupageBuildRuleTemplate.drt
fullstop-whitelist/src/test/java/org/zalando/stups/fullstop/whitelist/TaupageBuildRulesTest.java
fullstop-whitelist/src/test/resources/drools/TestRuleTemplate.drt
pom.xml

first naive whitelisting approach with drools

#312 added whitelisting feature

---

fullstop-core/fullstop-processing/pom.xml
fullstop-core/fullstop-processing/src/main/java/org/zalando/stups/fullstop/PluginEventsProcessor.java
fullstop-testing/it/fullstop/src/main/java/org/zalando/stups/fullstop/hystrix/HystrixKioOperations.java
fullstop-testing/it/fullstop/src/main/java/org/zalando/stups/fullstop/hystrix/HystrixTeamOperations.java

#315 fix HystrixExceptions

---

fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/rds/FetchRdsJob.java

#311 - fix nullpointer

---

fullstop-plugins/fullstop-instance-plugin-support/pom.xml
fullstop-plugins/fullstop-instance-plugin-support/src/main/java/org/zalando/stups/fullstop/plugin/impl/EC2InstanceContextImpl.java
fullstop-plugins/fullstop-instance-plugin-support/src/main/java/org/zalando/stups/fullstop/plugin/provider/impl/AmiIdProviderImpl.java
fullstop-plugins/fullstop-instance-plugin-support/src/main/java/org/zalando/stups/fullstop/plugin/provider/impl/KioVersionProviderImpl.java
fullstop-plugins/fullstop-instance-plugin-support/src/test/java/org/zalando/stups/fullstop/plugin/provider/impl/KioVersionProviderImplTest.java

#324-version id must not be blank

---

fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ec2/FetchEC2Job.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/rds/FetchRdsJob.java

#320 catch rate limit for jobs

---

fullstop-plugins/fullstop-instance-plugin-support/src/main/java/org/zalando/stups/fullstop/plugin/impl/EC2InstanceContextImpl.java
fullstop-plugins/fullstop-instance-plugin-support/src/test/java/org/zalando/stups/fullstop/plugin/impl/EC2InstanceContextImplTest.java

#327 fix double to string cast exception

---

fullstop-aws-support/fullstop-aws-userdata-support/src/main/java/org/zalando/stups/fullstop/events/UserDataProvider.java
fullstop-plugins/fullstop-instance-plugin-support/src/main/java/org/zalando/stups/fullstop/plugin/provider/impl/TaupageYamlProviderImpl.java
fullstop-plugins/fullstop-instance-plugin-support/src/test/java/org/zalando/stups/fullstop/plugin/provider/impl/TaupageYamlProviderImplTest.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/service/impl/ApplicationLifecycleServiceImpl.java

#337 fix classCastException

---

fullstop-whitelist/src/main/java/org/zalando/stups/fullstop/whitelist/config/WhitelistConfig.java

fixes #336 
There was no real bug, but we had a wrong config in our database. However, I added some logging to avoid this in the future.

#336 added some log output, when refreshing the whitelisting rules

---

fullstop-apis/fullstop-plugin-api/pom.xml
fullstop-apis/fullstop-violation-api/pom.xml
fullstop-aws-support/pom.xml
fullstop-core/pom.xml
fullstop-it/pom.xml
fullstop-job-launcher/pom.xml
fullstop-jobs/pom.xml
fullstop-logging/pom.xml
fullstop-parent-poms/fullstop-parent/pom.xml
fullstop-plugins/fullstop-instance-plugin-support/src/test/java/org/zalando/stups/fullstop/plugin/provider/impl/PieroneTagProviderImplTest.java
fullstop-plugins/fullstop-instance-plugin-support/src/test/java/org/zalando/stups/fullstop/plugin/provider/impl/ScmSourceProviderImplTest.java
fullstop-plugins/pom.xml
fullstop-testing/pom.xml
fullstop-violation/pom.xml
fullstop-web/fullstop-timemachine/pom.xml
fullstop-web/fullstop-violations-rest/pom.xml
fullstop-web/fullstop-web-commons/pom.xml
fullstop-web/fullstop-web-test-support/pom.xml
fullstop/pom.xml
pom.xml
team-service-api/pom.xml
teams-service-client-spring/pom.xml

#330 upgrade cloudtrail lib

---

fullstop-aws-support/fullstop-aws-cloudtrail-support/src/main/java/org/zalando/stups/fullstop/events/CloudTrailEventSupport.java
fullstop-aws-support/fullstop-aws-cloudtrail-support/src/test/java/org/zalando/stups/fullstop/events/CloudTrailEventSupportTest.java
fullstop-aws-support/fullstop-aws-cloudtrail-support/src/test/resources/empty-security-groups.json
fullstop-plugins/fullstop-save-securitygroups-plugin/src/main/java/org/zalando/stups/fullstop/plugin/SaveSecurityGroupsPlugin.java

#341 fixed save security group plugin

---

fullstop-apis/fullstop-plugin-api/pom.xml
fullstop-apis/fullstop-violation-api/pom.xml
fullstop-aws-support/pom.xml
fullstop-core/pom.xml
fullstop-it/pom.xml
fullstop-job-launcher/pom.xml
fullstop-jobs/pom.xml
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/impl/AccountIdSupplierImpl.java
fullstop-logging/pom.xml
fullstop-parent-poms/fullstop-parent/pom.xml
fullstop-plugins/pom.xml
fullstop-testing/pom.xml
fullstop-violation/pom.xml
fullstop-web/fullstop-timemachine/pom.xml
fullstop-web/fullstop-violations-rest/pom.xml
fullstop-web/fullstop-violations-rest/src/test/java/org/zalando/stups/fullstop/web/controller/ViolationsControllerTest.java
fullstop-web/fullstop-web-commons/pom.xml
fullstop-web/fullstop-web-test-support/pom.xml
fullstop/pom.xml
fullstop/src/main/java/org/zalando/stups/fullstop/hystrix/HystrixTeamOperations.java
pom.xml
team-service-api/pom.xml
team-service-api/src/main/java/org/zalando/stups/fullstop/teams/Account.java
team-service-api/src/main/java/org/zalando/stups/fullstop/teams/TeamOperations.java
teams-service-client-spring/pom.xml
teams-service-client-spring/src/main/java/org/zalando/stups/fullstop/teams/RestTemplateTeamOperations.java

#346 aws accounts disabled flag

---

fullstop-plugins/fullstop-save-securitygroups-plugin/src/main/java/org/zalando/stups/fullstop/plugin/SaveSecurityGroupsPlugin.java
fullstop-plugins/fullstop-save-securitygroups-plugin/src/main/java/org/zalando/stups/fullstop/plugin/SecurityGroupProvider.java
fullstop-plugins/fullstop-save-securitygroups-plugin/src/test/java/org/zalando/stups/fullstop/plugin/SaveSecurityGroupsPluginTest.java
fullstop-plugins/fullstop-save-securitygroups-plugin/src/test/java/org/zalando/stups/fullstop/plugin/SecurityGroupProviderTest.java

#351-log as warn

---

fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/iam/NoPasswordViolationWriter.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/iam/NoPasswordsJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/iam/csv/CredentialReportCSVParserImpl.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/iam/NoPasswordJobTest.java

#362 fix when password is empty

---

fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/iam/NoPasswordViolationWriter.java

#362 random uuid to avoid unique constraint

---

fullstop-web/fullstop-timemachine/src/main/java/org/zalando/stups/fullstop/swagger/api/FullstopApi.java
fullstop-web/fullstop-violations-rest/src/main/java/org/zalando/stups/fullstop/web/controller/ViolationsController.java
fullstop-web/fullstop-violations-rest/src/test/java/org/zalando/stups/fullstop/web/controller/ViolationsControllerTest.java
fullstop-web/fullstop-web-commons/src/main/java/org/zalando/stups/fullstop/web/api/ApiException.java
fullstop-web/fullstop-web-commons/src/main/java/org/zalando/stups/fullstop/web/api/ForbiddenException.java
fullstop-web/fullstop-web-commons/src/main/java/org/zalando/stups/fullstop/web/api/NotFoundException.java
fullstop-web/fullstop-web-commons/src/main/java/org/zalando/stups/fullstop/web/controller/ApiExceptionHandler.java
fullstop-web/fullstop-web-test-support/src/main/java/org/zalando/stups/fullstop/web/test/ControllerTestConfig.java
fullstop-web/fullstop-whitelisting-rules/src/main/java/org/zalando/stups/fullstop/controller/RuleController.java
fullstop-web/fullstop-whitelisting-rules/src/test/java/org/zalando/stups/fullstop/controller/RuleControllerTest.java
fullstop/src/main/java/org/zalando/stups/fullstop/hystrix/HystrixTeamOperations.java
fullstop/src/test/java/org/zalando/stups/fullstop/hystrix/HystrixTeamOperationsTest.java
team-service-api/src/main/java/org/zalando/stups/fullstop/teams/TeamOperations.java
team-service-client-spring/src/main/java/org/zalando/stups/fullstop/teams/RestTemplateTeamOperations.java

- users from teams without aws account can now use whitelisting api
- moved apiExceptioHandler so it will actually be used

#370 fix auth problem

---

fullstop-violation/fullstop-violation-persister-jpa/src/main/resources/db/migration/V9__update_violation_type_scm_source_json_missing.sql

update violation type

---

fullstop-plugins/fullstop-instance-plugin-support/src/main/java/org/zalando/stups/fullstop/plugin/provider/impl/TaupageYamlProviderImpl.java

#361 fetch more exceptions

---

.zappr.yml
fullstop-web/fullstop-violations-rest/src/main/java/org/zalando/stups/fullstop/web/converter/ViolationEntityToDtoConverter.java
fullstop-web/fullstop-violations-rest/src/main/java/org/zalando/stups/fullstop/web/model/Violation.java
fullstop-web/fullstop-violations-rest/src/test/java/org/zalando/stups/fullstop/web/converter/ViolationEntityToDtoConverterTest.java

add rule entity in dto

---

fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/repository/ViolationRepositoryCustom.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/repository/impl/ViolationRepositoryImpl.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/service/ViolationService.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/service/impl/ViolationServiceImpl.java
fullstop-violation/fullstop-violation-jpa/src/test/java/org/zalando/stups/fullstop/violation/repository/ViolationRepositoryTest.java
fullstop-web/fullstop-violations-rest/src/main/java/org/zalando/stups/fullstop/web/controller/ViolationsController.java
fullstop-web/fullstop-violations-rest/src/main/java/org/zalando/stups/fullstop/web/controller/ViolationsCountController.java
fullstop-web/fullstop-violations-rest/src/test/java/org/zalando/stups/fullstop/web/controller/ViolationsControllerTest.java
fullstop-web/fullstop-violations-rest/src/test/java/org/zalando/stups/fullstop/web/controller/ViolationsCountControllerTest.java

#378 api defaults resolved whitelisted

---

fullstop-plugins/fullstop-save-securitygroups-plugin/src/main/java/org/zalando/stups/fullstop/plugin/SaveSecurityGroupsPlugin.java
fullstop-plugins/fullstop-save-securitygroups-plugin/src/test/java/org/zalando/stups/fullstop/plugin/SaveSecurityGroupsPluginTest.java
fullstop-plugins/fullstop-save-securitygroups-plugin/src/test/resources/run-instance-record.json

#380 use final variable

---

fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/entity/ViolationTypeEntity.java
fullstop-violation/fullstop-violation-persister-jpa/src/main/resources/db/migration/V10__add_priority.sql
fullstop-web/fullstop-violations-rest/src/main/java/org/zalando/stups/fullstop/web/converter/ViolationTypeEntityToDtoConverter.java
fullstop-web/fullstop-violations-rest/src/main/java/org/zalando/stups/fullstop/web/model/ViolationType.java
fullstop-web/fullstop-violations-rest/src/test/java/org/zalando/stups/fullstop/web/controller/ViolationTypesControllerTest.java

add priority

---

fullstop/src/main/java/org/zalando/stups/fullstop/config/OAuth2Configuration.java

#389 Allow HTTP OPTIONS for everyone.

---

README.md
fullstop-jobs/README.md
fullstop-plugins/fullstop-application-masterdata-plugin/README.md
fullstop-plugins/fullstop-taupage-yaml-plugin/README.md

#394 add documentation

---

fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/repository/LifecycleRepositoryCustom.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/repository/impl/LifecycleRepositoryImpl.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/service/ApplicationLifecycleService.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/service/impl/ApplicationLifecycleServiceImpl.java
fullstop-violation/fullstop-violation-jpa/src/test/java/org/zalando/stups/fullstop/violation/repository/LifecycleRepositoryTest.java
fullstop-web/fullstop-lifecycle-api/README.md
fullstop-web/fullstop-lifecycle-api/src/main/java/org/zalando/stups/fullstop/web/controller/LifecycleController.java
fullstop-web/fullstop-lifecycle-api/src/test/java/org/zalando/stups/fullstop/web/controller/LifecycleControllerTest.java

#391 add parameter to lifecycle controller

---

fullstop-plugins/fullstop-instance-plugin-support/src/main/java/org/zalando/stups/fullstop/plugin/impl/EC2InstanceContextImpl.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/repository/impl/LifecycleRepositoryImpl.java

#391 filter by version

---

fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/repository/impl/ViolationRepositoryImpl.java
fullstop-violation/fullstop-violation-persister-jpa/src/main/resources/db/migration/V13__add_indices.sql

#399 add indices and remove unnecessary joins for ruleEntity

---

fullstop-plugins/fullstop-instance-plugin-support/src/test/java/org/zalando/stups/fullstop/plugin/provider/impl/TaupageYamlProviderImplTest.java

#401 add tests

---

docs/violations.dot
fullstop-apis/fullstop-violation-api/src/main/java/org/zalando/stups/fullstop/violation/DefaultViolation.java
fullstop-apis/fullstop-violation-api/src/main/java/org/zalando/stups/fullstop/violation/Violation.java
fullstop-apis/fullstop-violation-api/src/main/java/org/zalando/stups/fullstop/violation/ViolationBuilder.java
fullstop-it/src/test/java/org/zalando/stups/fullstop/whitelist/WhitelistRulesEvaluatorTest.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ami/FetchAmiJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/FetchTaupageYaml.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/impl/FetchTaupageYamlImpl.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ec2/FetchEC2Job.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/scm/ScmCommitsJob.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/common/impl/FetchTaupageYamlImplTest.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJobTest.java
fullstop-plugins/fullstop-instance-plugin-support/src/main/java/org/zalando/stups/fullstop/plugin/impl/EC2InstanceContextImpl.java
fullstop-plugins/fullstop-region-plugin/src/test/java/org/zalando/stups/fullstop/plugin/RegionPluginTest.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/entity/Stack.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/entity/ViolationEntity.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/service/ApplicationVersionService.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/service/impl/ApplicationVersionServiceImpl.java
fullstop-violation/fullstop-violation-jpa/src/test/java/org/zalando/stups/fullstop/violation/repository/ViolationRepositoryTest.java
fullstop-violation/fullstop-violation-jpa/src/test/java/org/zalando/stups/fullstop/violation/service/impl/ApplicationVersionServiceImplTest.java
fullstop-violation/fullstop-violation-persister-jpa/src/main/java/org/zalando/fullstop/violation/persist/jpa/ViolationJpaPersister.java
fullstop-violation/fullstop-violation-persister-jpa/src/main/java/org/zalando/fullstop/violation/persist/jpa/config/ViolationJpaPersisterAutoConfiguration.java
fullstop-violation/fullstop-violation-persister-jpa/src/main/resources/db/migration/V14__add_columns_to_violations.sql
fullstop-web/fullstop-violations-rest/src/main/java/org/zalando/stups/fullstop/web/model/Violation.java
fullstop-whitelist/src/main/java/org/zalando/stups/fullstop/whitelist/WhitelistRulesEvaluator.java

#396 application version in violation

---

fullstop-jobs/pom.xml
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/AmiDetailsProvider.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/EC2InstanceProvider.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/impl/AmiDetailsProviderImpl.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/impl/EC2InstanceProviderImpl.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/config/CacheConfig.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ec2/FetchEC2Job.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJob.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJobTest.java
fullstop-plugins/fullstop-keypair-plugin/src/main/java/org/zalando/stups/fullstop/plugin/keypair/KeyPairPlugin.java
fullstop-plugins/fullstop-keypair-plugin/src/test/java/org/zalando/stups/fullstop/plugin/keypair/KeyPairPluginTest.java

404 put ami name to meta info

---

fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/config/CacheConfig.java

#411 fix cache config

---

fullstop-apis/fullstop-violation-api/src/main/java/org/zalando/stups/fullstop/violation/ViolationBuilder.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ec2/FetchEC2Job.java

#413 fixes typo that lead to error. Finalize some vars

---

fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/entity/ViolationTypeEntity.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/violation/repository/impl/ViolationRepositoryImpl.java
fullstop-web/fullstop-violations-rest/src/main/java/org/zalando/stups/fullstop/web/converter/ViolationEntityToDtoConverter.java
fullstop-web/fullstop-violations-rest/src/main/java/org/zalando/stups/fullstop/web/converter/ViolationTypeEntityToDtoConverter.java
fullstop-web/fullstop-violations-rest/src/main/java/org/zalando/stups/fullstop/web/model/Violation.java
fullstop-web/fullstop-violations-rest/src/main/java/org/zalando/stups/fullstop/web/model/ViolationType.java

#419 remove join

---

fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/rule/service/RuleEntityService.java
fullstop-violation/fullstop-violation-jpa/src/main/java/org/zalando/stups/fullstop/rule/service/impl/RuleEntityServiceImpl.java
fullstop-violation/fullstop-violation-jpa/src/test/java/org/zalando/stups/fullstop/rule/service/impl/RuleEntityServiceImplTest.java
fullstop-web/fullstop-whitelisting-rules/src/main/java/org/zalando/stups/fullstop/controller/RuleController.java
fullstop-web/fullstop-whitelisting-rules/src/test/java/org/zalando/stups/fullstop/controller/RuleControllerTest.java
fullstop-whitelist/src/main/java/org/zalando/stups/fullstop/whitelist/config/WhitelistConfig.java

#417 implemented DELETE endpoint for whitelisting rules

---

fullstop/src/main/resources/log4j2.xml

fixes #418
deactivate log for class. waiting for spring boot fix.

#418 remove log

---

.zappr.yml

#438 make .zappr.yaml compliant to the new approval flow

---

fullstop/src/main/resources/log4j2.xml

#444 do not log "EventVersion 1.04 is not supported by CloudTrail"

---

fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/config/HttpClientConfig.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ec2/FetchEC2Job.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJob.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJobTest.java

Add custom user agent to job requests

---

fullstop-plugins/fullstop-unapproved-services-and-role-plugin/pom.xml
fullstop-plugins/fullstop-unapproved-services-and-role-plugin/src/main/java/org/zalando/stups/fullstop/plugin/unapproved/UnapprovedServicesAndRolePlugin.java
fullstop-plugins/fullstop-unapproved-services-and-role-plugin/src/test/java/org/zalando/stups/fullstop/plugin/unapproved/UnapprovedServicesAndRolePluginTest.java

#457 use JsonDiff to compare roloe policies

---

fullstop-job-launcher/Dockerfile
fullstop/Dockerfile

Switch to the latest base image.

upgrade-docker-base-images

---

fullstop-plugins/fullstop-unapproved-services-and-role-plugin/src/main/java/org/zalando/stups/fullstop/plugin/unapproved/PolicyProvider.java
fullstop-plugins/fullstop-unapproved-services-and-role-plugin/src/main/java/org/zalando/stups/fullstop/plugin/unapproved/RolePolicies.java
fullstop-plugins/fullstop-unapproved-services-and-role-plugin/src/main/java/org/zalando/stups/fullstop/plugin/unapproved/UnapprovedServicesAndRolePlugin.java
fullstop-plugins/fullstop-unapproved-services-and-role-plugin/src/main/java/org/zalando/stups/fullstop/plugin/unapproved/impl/PolicyProviderImpl.java
fullstop-plugins/fullstop-unapproved-services-and-role-plugin/src/test/java/org/zalando/stups/fullstop/plugin/unapproved/PolicyProviderTest.java
fullstop-plugins/fullstop-unapproved-services-and-role-plugin/src/test/java/org/zalando/stups/fullstop/plugin/unapproved/UnapprovedServicesAndRolePluginTest.java

460 fix policy modification check

---

fullstop-plugins/fullstop-unapproved-services-and-role-plugin/src/main/java/org/zalando/stups/fullstop/plugin/unapproved/UnapprovedServicesAndRolePlugin.java

I just forgot this small change in the previous pull request for #460

show error messages on MODIFIED_ROLE_OR_SERVICE

---

fullstop/pom.xml
fullstop/src/main/java/org/zalando/stups/fullstop/config/CacheConfig.java
team-service-api/pom.xml
team-service-api/src/main/java/org/zalando/stups/fullstop/teams/TeamOperations.java

#463 cache alle TeamOperations

---

fullstop-job-launcher/Dockerfile
fullstop/Dockerfile

Upgrade docker base

---

fullstop-job-launcher/Dockerfile
fullstop/Dockerfile

update docker base image

---

fullstop-apis/fullstop-violation-api/src/main/java/org/zalando/stups/fullstop/violation/ViolationType.java
fullstop-plugins/fullstop-registry-plugin/src/main/java/org/zalando/stups/fullstop/plugin/DockerRegistryPlugin.java
fullstop-plugins/fullstop-registry-plugin/src/test/java/org/zalando/stups/fullstop/plugin/DockerRegistryPluginTest.java
fullstop-violation/fullstop-violation-persister-jpa/src/main/resources/db/migration/V15__add_dirty_build_violation.sql

Dirty builds

---

fullstop-aws-support/fullstop-aws-client-support/pom.xml
fullstop-aws-support/fullstop-aws-client-support/src/main/java/org/zalando/stups/fullstop/aws/AwsRequestUtil.java
fullstop-aws-support/fullstop-aws-client-support/src/test/java/org/zalando/stups/fullstop/aws/AwsRequestUtilTest.java
fullstop-aws-support/fullstop-aws-client-support/src/test/resources/log4j2.xml
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ami/FetchAmiJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/impl/AmiDetailsProviderImpl.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/impl/EC2InstanceProviderImpl.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/impl/FetchTaupageYamlImpl.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/impl/SecurityGroupsCheckerImpl.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ec2/FetchEC2Job.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/iam/IdentityManagementDataSource.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/policy/CrossAccountPolicyForIAMJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/rds/FetchRdsJob.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/rds/FetchRdsJobTest.java
fullstop-plugins/fullstop-instance-plugin-support/src/main/java/org/zalando/stups/fullstop/plugin/provider/impl/AmiIdProviderImpl.java
fullstop-plugins/fullstop-instance-plugin-support/src/main/java/org/zalando/stups/fullstop/plugin/provider/impl/AmiProviderImpl.java
fullstop-plugins/fullstop-instance-plugin-support/src/main/java/org/zalando/stups/fullstop/plugin/provider/impl/TaupageYamlProviderImpl.java
fullstop-plugins/fullstop-save-securitygroups-plugin/src/main/java/org/zalando/stups/fullstop/plugin/SecurityGroupProvider.java
fullstop-plugins/fullstop-subnet-plugin/src/main/java/org/zalando/stups/fullstop/plugin/subnet/SubnetPlugin.java
fullstop-plugins/fullstop-unapproved-services-and-role-plugin/src/main/java/org/zalando/stups/fullstop/plugin/unapproved/impl/PolicyProviderImpl.java

* created an AwsRequestUtil, to wrap aws api interactions and handle request limit errors by retrying thr request up to 10 times with exponential backoff
fixes #443

retry on AWS rate limit or throttling

---

fullstop-plugins/fullstop-registry-plugin/src/main/java/org/zalando/stups/fullstop/plugin/DockerRegistryPlugin.java
fullstop-plugins/fullstop-registry-plugin/src/test/java/org/zalando/stups/fullstop/plugin/DockerRegistryPluginTest.java

#475 check for 'false' in scm-source.json status fields.

---

fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ami/FetchAmiJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ec2/FetchEC2Job.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/iam/IdentityManagementDataSource.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/policy/CrossAccountPolicyForIAMJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/rds/FetchRdsJob.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/ami/FetchAmiJobTest.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/policy/CrossAccountPolicyForIAMJobTest.java

All Jobs in Fullstop were lacking the handling of large, paged result sets returned by the AWS API.

Fix fetching paged results

---

fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/scm/ScmCommitsJob.java

No violations for disabled accounts

---

fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/rds/FetchRdsJob.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/rds/FetchRdsJobTest.java

Make sure that each RDS violation has its own metadata (fixes #479)

---

fullstop-job-launcher/Dockerfile
fullstop/Dockerfile

Use latest Docker images

---

fullstop-plugins/fullstop-unapproved-services-and-role-plugin/src/main/java/org/zalando/stups/fullstop/plugin/unapproved/UnapprovedServicesAndRolePlugin.java
fullstop-plugins/fullstop-unapproved-services-and-role-plugin/src/main/java/org/zalando/stups/fullstop/plugin/unapproved/config/UnapprovedServicesAndRoleProperties.java
fullstop-plugins/fullstop-unapproved-services-and-role-plugin/src/test/java/org/zalando/stups/fullstop/plugin/unapproved/UnapprovedServicesAndRolePluginTest.java
fullstop-plugins/fullstop-unapproved-services-and-role-plugin/src/test/resources/admin-record.json

MODIFIED_ROLE_OR_SERVICE violations should not be reported if the user who performed the change was an administrator.

skip ModifiedRolePlugin on admin changes

---

fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/impl/FetchTaupageYamlImpl.java
fullstop-plugins/fullstop-instance-plugin-support/src/main/java/org/zalando/stups/fullstop/plugin/provider/impl/TaupageYamlProviderImpl.java

Catch a more general type of YAMLExceptions when tryibg to parse TaupageConfig

catch more YAML errors

---

fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ami/FetchAmiJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ec2/FetchEC2Job.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/exception/JobExceptionHandler.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/exception/JobExceptionHandlerImpl.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/iam/KeyRotationJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/iam/NoPasswordsJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/policy/CrossAccountPolicyForIAMJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/rds/FetchRdsJob.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/ami/FetchAmiJobTest.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJobTest.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/exception/JobExceptionHandlerImplTest.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/iam/KeyRotationJobTest.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/iam/NoPasswordJobTest.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/policy/CrossAccountPolicyForIAMJobTest.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/rds/FetchRdsJobTest.java

prevent jobs from crashing if only one check in one aws account fails

handle job exceptions

---

fullstop-jobs/pom.xml
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/SecurityGroupCheckDetails.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/SecurityGroupsChecker.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/impl/SecurityGroupsCheckerImpl.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ec2/FetchEC2Job.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/utils/Predicates.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/common/impl/SecurityGroupsCheckerImplTest.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJobTest.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/utils/PredicatesTest.java

* correctly handle private IP ranges.
* add IPv6 support
* distinguish protocols (tcp, icmp, udp, ...)
Fixes #487

Fix security groups check

---

fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ami/FetchAmiJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/impl/EC2InstanceProviderImpl.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ec2/FetchEC2Job.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/rds/FetchRdsJob.java

* catch inner exceptions to be able to proceed with remaining ELBs / instances
* don't fail on not found instance ids

make jobs more resilient

---

fullstop-aws-support/fullstop-aws-client-support/src/main/java/org/zalando/stups/fullstop/aws/CachingClientProvider.java

we run into RequestLimitExceeded quite often. Let's see if increasing this value already helps.

increase max retries

---

team-service-client-spring/src/main/java/org/zalando/stups/fullstop/teams/RestTemplateTeamOperations.java

* fetching also accounts the user has the k8s production deployer role for

#507 fetch k8s accounts the user has access to

---

fullstop-violation/fullstop-violation-persister-jpa/src/main/resources/db/migration/V16__create_lambda_function_created_from_untrusted_location_type.sql

adding missing migration script for lambda #512

add db migration

---

fullstop/pom.xml

added lambda plugin in main pom

#512 lambda plugin added

---

fullstop-violation/fullstop-violation-persister-jpa/src/main/resources/db/migration/V17__add_lambda_priority.sql

add priority value for new type

#512 add lambda prio

---

fullstop-plugins/fullstop-lambda-plugin/src/main/java/org/zalando/stups/fullstop/plugin/lambda/LambdaPlugin.java

#512 add metainfo for lambda plugin

---

fullstop-whitelist/README.md

Add a README to explain all the feature of the whitelisting engine.

document the whitelisting engine

---

fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJob.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJobTest.java

The ELB check currently does not make sense for Kubernetes-managed ELBs.
Let's ignore those for now, to avoid spamming the people with false-positives.

ignore Kubernetes ELBs

---

fullstop-plugins/fullstop-lambda-plugin/src/main/java/org/zalando/stups/fullstop/plugin/lambda/LambdaPlugin.java
fullstop-plugins/fullstop-lambda-plugin/src/test/java/org/zalando/stups/lambda/LambdaPluginTest.java
fullstop-plugins/fullstop-lambda-plugin/src/test/resources/record-update-wrong-s3bucket-whitelisted-codesha256.json

add whitelisting rule for lambda aws console code

add whitelist for lambda code

---

fullstop-aws-support/fullstop-aws-s3-support/src/main/java/org/zalando/stups/fullstop/s3/S3Service.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ami/FetchAmiJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ec2/FetchEC2Job.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/iam/KeyRotationJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/iam/NoPasswordsJob.java
fullstop-web/fullstop-timemachine/src/main/java/org/zalando/stups/fullstop/swagger/api/FullstopApi.java
fullstop/src/main/resources/log4j2.xml

log less information

---

fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJob.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/elb/FetchElasticLoadBalancersJobTest.java

fix ELB describeTags usage

---

fullstop-plugins/fullstop-save-securitygroups-plugin/pom.xml

groovy and spock are in the list of dependencies, but they are not used at all

remove groovy dependencies

---

fullstop/src/main/resources/config/application.yml

audi events logging
```
logging:
  level:
    org.springframework.boot:
      actuate:
        audit:
          listener: debug
```

try to log audit events

---

fullstop/src/main/resources/config/application.yml

reverted changes of the last commit in regards of audit logs

revert audit changes

---

fullstop/src/main/resources/log4j2.xml

AuditListener to debug

---

fullstop-violation/fullstop-violation-jpa/src/test/java/org/zalando/stups/fullstop/violation/repository/ViolationRepositoryTest.java
fullstop-web/fullstop-violations-rest/src/main/java/org/zalando/stups/fullstop/web/controller/ViolationsController.java

fixes #553 
While the list of "type" parameters for the query was compiled, a `null` entry sneaked in and caused the exception.

Fix internal server error

---

fullstop-whitelist/README.md

Added example how to whitelist a CROSS_ACCOUNT_ROLE violation.

whitelist example

---

delivery.yaml
fullstop-job-launcher/Dockerfile
fullstop/Dockerfile

build with CDP

---

fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/ami/FetchAmiJob.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/TaupageExpirationTimeProvider.java
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/common/impl/TaupageExpirationTimeProviderImpl.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/ami/FetchAmiJobTest.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/common/impl/TaupageExpirationTimeProviderImplTest.java

Taupage expiration by tag

---

fullstop-aws-support/fullstop-aws-client-support/pom.xml
fullstop-aws-support/fullstop-aws-client-support/src/main/java/org/zalando/stups/fullstop/aws/CachingClientProvider.java
fullstop-aws-support/fullstop-aws-client-support/src/test/java/org/zalando/stups/fullstop/aws/CachingClientProviderTest.java
fullstop-aws-support/fullstop-aws-client-support/src/test/java/org/zalando/stups/fullstop/aws/ClientTest.java
fullstop-aws-support/fullstop-aws-s3-support/src/main/java/org/zalando/stups/fullstop/s3/S3Service.java
fullstop-aws-support/fullstop-aws-s3-support/src/test/java/org/zalando/stups/fullstop/s3/S3ServiceTest.java
fullstop-core/fullstop-processing/src/test/java/org/zalando/stups/fullstop/plugin/example/ExamplePlugin.java
fullstop-it/src/test/resources/config/application-integration-test.yml
fullstop-jobs/pom.xml
fullstop-jobs/src/main/java/org/zalando/stups/fullstop/jobs/config/HttpClientConfig.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/TestAsyncIT.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/config/HttpClientConfigTest.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/iam/NoPasswordJobTest.java
fullstop-jobs/src/test/java/org/zalando/stups/fullstop/jobs/rds/FetchRdsJobTest.java
fullstop-violation/fullstop-violation-jpa/src/test/java/org/zalando/stups/fullstop/violation/service/impl/ApplicationVersionServiceImplTest.java
fullstop-violation/fullstop-violation-jpa/src/test/java/org/zalando/stups/fullstop/violation/service/impl/SaveApplicationLifecycleRetryTest.java
fullstop-web/fullstop-timemachine/src/main/java/org/zalando/stups/fullstop/swagger/api/FullstopApi.java
fullstop-web/fullstop-timemachine/src/main/java/org/zalando/stups/fullstop/swagger/configuration/SwaggerConfig.java
fullstop-web/fullstop-violations-rest/src/test/java/org/zalando/stups/fullstop/web/controller/ViolationsControllerTest.java
fullstop-whitelist/src/main/java/org/zalando/stups/fullstop/whitelist/WhitelistRulesEvaluator.java
pom.xml

* fix "unchecked" warnings
* fix deprecation warnings
* upgrade aws sdk to support `close` method on STSCredentialsProvider

fix compiler warnings

---

fullstop-web/fullstop-violations-rest/src/main/java/org/zalando/stups/fullstop/web/controller/ViolationsController.java

- added authorization with scope annotation to POST method

scope authorization
